### ISSUE TITLE
[v3] Consider updating displayName size to be >= name

### ISSUE THREAD

**Issue by rido-min** [Azure/opendigitaltwins-dtdl#145]
In v3 the `name` limit has been increased from 64 to 512. 
I guess the `displayName` should be equal or greater than `name`

**Comment by rido-min** [comment]
@jrdouceur can we consider this for v3 ?

**Comment by jrdouceur** [comment]
I suppose we could run this by the DSC, too.  I had thought this was a deliberate omission from the previous change proposal, since the stated motivation for increasing the limit on `name` does not seem to apply to `displayName`.  Also, a very long `displayName` could have a negative effect on a generated UI, so there seems potentially more risk to this.

**Comment by rido-min** [comment]
AFAIK this was not a deliberated omission. I don't see any risk of increasing `displayName` size. Will be weird to have longer names than displayNames. I'm not aware of any generated UI tool, but if any, it can always shrink the string to whatever size fits in the UI.

**Comment by jrdouceur** [comment]
I have no objection to this change.  Feel free to follow the same course of action as with the increase to `name` length limit.  I suspect the DSC will close on it quickly.

**Comment by rido-min** [comment]
closed with #154
