### ISSUE TITLE
[DTDLv3] Partner Extension `@context` DTMI set to IoT Central. Should be more generic.

### ISSUE THREAD

**Issue by thern743** [Azure/opendigitaltwins-dtdl#157]
It seems more appropriate that the IoT Central partner extensions have a more generic @context (such as Microsoft/Azure/IoT) instead of IoT Central as a specific solution. For instance, if IoT Central were to change (or become deprecated) it wouldn't make sense to have an orphaned or misaligned @context. Also, if Microsoft offers the same extensions in another service, such as Azure Digital Twins (ADT), IoT Hub, or Azure Device Update (ADU), it would be confusing to have an @context that was duplicated, mixed, or overlapping with an adjacent but irreverent service. Overall, it makes sense to offer these extensions more broadly under a generic context since they aren't intrinsic to IoT Central.

**Comment by jrdouceur** [comment]
The concept of DTDL "partner extensions" is being deprecated in favor of "feature extensions".  Instead of extensions defined for the needs of specific partner services such as IoT Central, DTDL is now employing extensions that each provide a specific language feature intended to have wider applicability than a single service.  Examples include [Historization](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v3/DTDL.historization.v1.md), [Streaming](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v3/DTDL.streaming.v1.md), and [Annotation](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v3/DTDL.annotation.v1.md).
