### ISSUE TITLE
Questions: Telemetry on DT

### ISSUE THREAD

**Issue by maxstefaniv** [Azure/opendigitaltwins-dtdl#94]
To whom it may concern, I hope you can understand my issue and give me some answers.
I have some issues finding out and understanding the proper use of a Telemetry on DT as well as the proper generation and consumption. Let me elaborate and ask proper questions:
- On [DTDL Version1](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v1-preview/dtdlv1.md#telemetry), it states that "Telemetry describes the data emitted by a device or digital twin.." and on [DTDL Version2](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md) it states that "Telemetry describes the data emitted by any digital twin...".
All the examples and documentations on DT that I was able to find uses IoT hub Telemetry to overwrite a Property field on DT. Next step being a function that reads that Property and propagates it through DT or out. [End-to-end solution](https://docs.microsoft.com/en-us/azure/digital-twins/tutorial-end-to-end) this is the example. 
In order to do that DTDL json Model needs to have declared that property on a created DT.
Question: How is that I can generate Telemetry messages on behalf of a DT without the need of defining that value on a DT as a Telemetry using: `client.PublishTelemetryAsync(twinId, Guid.NewGuid().ToString(), "{\"Telemetry1\": 5}"); ` [Git Repo](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/PublishTelemetrySamples.cs)?
Let me elaborate more:
```{
            "name": "Temperature",
            "@type": [
                "Telemetry",
                "Temperature"
            ],
            "description": "Temperature characteristics",
            "schema": "double",
            "unit": "degreeCelsius"
        },
```
This is what I declared on my DT. and the above call to `client.PublishTelemetryAsync` is what I am sending on behalf of this DT. Through event stream the message is sent as telemetry from defined by ID Digital Twin. So the second function that reads, as explained ->[Data flow](https://docs.microsoft.com/en-us/azure/digital-twins/concepts-route-events): Digital Twin Change Notification, Digital Twin Lifecycle Notification, Digital Twin Relationship Change Notification and Digital Twin Telemetry Messages will detect a Telemetry name: Telemetry1 (or whatever we want to call it).

 **Question** : Why declare on a DT a Telemetry when in order to emit Telemetry data on behalf of a DT there is no validation with DT for existence of that field?
- I also noted that this generated Telemetry once detected on endpoint function is not properly consumed. I detect the telemetry a bunch of times when this Telemetry message should disappear once it is consumed on the endpoint.

**Final and most important questions**: 
Am I failing to understand how Telemetry is generated From or on behalf of a Digital Twin? 
Could someone link me a proper use example, as I failed to find it? 
Which is the value for declaring Schema, Unit, @Type for telemetry on DT when it looks like they are not used?

Thank you, very much, for your time.
Kind regards,
Max

**Comment by briancr-ms** [comment]
Thanks for your questions! Your questions include questions about DTDL (the modeling language) as well as Azure Digital Twins (the service, which uses DTDL for modeling). Azure Digital Twins is somewhat outside the scope of this GitHub repo and has its own support and troubleshooting resources available through the Azure Digital Twins portal or through Azure support resources (https://azure.microsoft.com/en-us/services/digital-twins/).

For your DTDL questions:
- It looks like the definition of your "Temperature" telemetry is valid DTDL and would describe a payload, written in JSON for example, like `{ "Temperature": 42 }`.

For your Azure Digital Twins (ADT) questions, which I will do my best to answer:
- ADT does not currently validate the telemetry payload against the DTDL model for the twin. You noticed this because you see ADT accept and send any telemetry for your digital twin when you send telemetry. This behavior comes from the desire to support device telemetry through device digital twins, where devices may send data that does not match what a model author may have written in the model.
- Even without this validation, modeling telemetry can be useful because it can indicate to your solution what telemetry is expected (especially if your solution is model driven). This enables your solution to take action on telemetry that does not match the model.
- When you send telemetry, the behavior of the message consumption depends on the behavior and configuration of the messaging service you're using. For example, if your telemetry message is written to an Azure Event Hub, then it will remain in that Event Hub for the configured time period (but a consumer can use checkpointing to only read new messages).
